In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("ecommerce_customer_behavior.csv")
df.head()

,Age,Gender,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,...,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,...,17.9,9.0,4.0,16.3,20.8,1.0,953.33,2278.0,0,Q1
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,...,42.8,7.0,3.0,NaN,23.3,3.0,1067.47,3028.0,0,Q4
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,...,0.0,4.0,1.0,NaN,8.8,NaN,1289.75,2317.0,0,Q4
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,...,41.4,2.0,5.0,85.9,31.0,3.0,2340.92,2674.0,0,Q1
4,35.0,Male,India,Delhi,3.1,29.0,51.4,NaN,19.1,9.0,...,37.9,1.0,11.0,83.0,50.4,4.0,3041.29,5354.0,0,Q4

In [7]:
df.shape

(50000, 25)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            47505 non-null  float64
 1   Gender                         50000 non-null  object
 2   Country                        50000 non-null  object
 3   City                           50000 non-null  object
 4   Membership_Years               50000 non-null  float64
 5   Login_Frequency                50000 non-null  float64
 6   Session_Duration_Avg           46601 non-null  float64
 7   Pages_Per_Session              47000 non-null  float64
 8   Cart_Abandonment_Rate          50000 non-null  float64
 9   Wishlist_Items                 46000 non-null  float64
 10  Total_Purchases                50000 non-null  float64
 11  Average_Order_Value            50000 non-null  float64
 12  Days_Since_Last_Purchase       47000 non-null  float64
 13  Discount_Usage_Rate            46500 non-null  float64
 14  Returns_Rate                   45509 non-null  float64
 15  Email_Open_Rate                47472 non-null  float64
 16  Customer_Service_Calls         49832 non-null  float64
 17  Product_Reviews_Written        46500 non-null  float64
 18  Social_Media_Engagement_Score  44000 non-null  float64
 19  Mobile_App_Usage               45000 non-null  float64
 20  Payment_Method_Diversity       47500 non-null  float64
 21  Lifetime_Value                 50000 non-null  float64
 22  Credit_Balance                 44500 non-null  float64
 23  Churned                        50000 non-null  int64
 24  Signup_Quarter                 50000 non-null  object
dtypes: float64(20), int64(1), object(4)
memory usage: 9.5+ MB

In [9]:
df.describe()

,Age,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,Total_Purchases,Average_Order_Value,Days_Since_Last_Purchase,...,Returns_Rate,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned
count,47505.000000,50000.000000,50000.000000,46601.000000,47000.000000,50000.000000,46000.000000,50000.000000,50000.000000,47000.000000,...,45509.000000,47472.000000,49832.000000,46500.000000,44000.000000,45000.000000,47500.000000,50000.000000,44500.000000,50000.000000
mean,37.802968,2.984009,11.624660,27.660754,8.737811,57.079973,4.298391,13.111576,123.117330,29.792872,...,6.680913,20.937980,5.681831,2.853312,29.364466,19.371607,2.353874,1440.626292,1966.233258,0.289000
std,11.834668,2.059105,7.810657,10.871013,3.778220,16.282723,3.189754,7.017312,175.569714,29.695062,...,6.143027,14.252561,2.676052,2.328948,20.574021,9.419252,1.110012,907.249443,1225.072166,0.453302
min,5.000000,0.100000,0.000000,1.000000,1.000000,0.000000,0.000000,-13.000000,26.380000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,29.000000,1.400000,6.000000,19.700000,6.000000,46.400000,2.000000,8.000000,87.050000,9.000000,...,2.900000,9.900000,4.000000,1.000000,13.200000,12.500000,2.000000,789.817500,1049.000000,0.000000
50%,38.000000,2.500000,11.000000,26.800000,8.400000,58.100000,4.000000,12.000000,112.970000,21.000000,...,5.400000,19.700000,5.000000,2.000000,27.600000,18.600000,2.000000,1243.415000,1896.000000,0.000000
75%,46.000000,4.000000,17.000000,34.700000,11.200000,68.700000,6.000000,17.000000,144.440000,41.000000,...,9.100000,30.400000,7.000000,4.000000,43.100000,25.500000,3.000000,1874.000000,2791.000000,1.000000
max,200.000000,10.000000,46.000000,75.600000,24.100000,143.743350,28.000000,128.700000,9666.379178,287.000000,...,99.615734,91.700000,21.000000,21.000000,100.000000,61.900000,5.000000,8987.240000,7197.000000,1.000000

In [10]:
df.nunique()

Age                                 62
Gender                               3
Country                              8
City                                40
Membership_Years                   200
Login_Frequency                     46
Session_Duration_Avg               658
Pages_Per_Session                  224
Cart_Abandonment_Rate             1000
Wishlist_Items                      25
Total_Purchases                    150
Average_Order_Value              16407
Days_Since_Last_Purchase           235
Discount_Usage_Rate               1727
Returns_Rate                       394
Email_Open_Rate                    720
Customer_Service_Calls              21
Product_Reviews_Written             18
Social_Media_Engagement_Score      972
Mobile_App_Usage                   540
Payment_Method_Diversity             5
Lifetime_Value                   45447
Credit_Balance                    5234
Churned                              2
Signup_Quarter                       4
dtype: int64

In [11]:
df.duplicated().sum()

0

In [12]:
missing = df.isnull().sum()

missing = missing[missing>0]

missing.sort_values(ascending=False)

Social_Media_Engagement_Score    6000
Credit_Balance                   5500
Mobile_App_Usage                 5000
Returns_Rate                     4491
Wishlist_Items                   4000
Discount_Usage_Rate              3500
Product_Reviews_Written          3500
Session_Duration_Avg             3399
Pages_Per_Session                3000
Days_Since_Last_Purchase         3000
Email_Open_Rate                  2528
Payment_Method_Diversity         2500
Age                              2495
Customer_Service_Calls            168
dtype: int64

In [13]:
(df.isnull().sum()/len(df))*100

Age                               4.990
Gender                            0.000
Country                           0.000
City                              0.000
Membership_Years                  0.000
Login_Frequency                   0.000
Session_Duration_Avg              6.798
Pages_Per_Session                 6.000
Cart_Abandonment_Rate             0.000
Wishlist_Items                    8.000
Total_Purchases                   0.000
Average_Order_Value               0.000
Days_Since_Last_Purchase          6.000
Discount_Usage_Rate               7.000
Returns_Rate                      8.982
Email_Open_Rate                   5.056
Customer_Service_Calls            0.336
Product_Reviews_Written           7.000
Social_Media_Engagement_Score    12.000
Mobile_App_Usage                 10.000
Payment_Method_Diversity          5.000
Lifetime_Value                    0.000
Credit_Balance                   11.000
Churned                           0.000
Signup_Quarter                    0.000
dtype: float64

In [14]:
df["Churned"].value_counts()

Churned
0    35550
1    14450
Name: count, dtype: int64

In [15]:
df["Churned"].value_counts(normalize=True)

Churned
0    0.711
1    0.289
Name: proportion, dtype: float64

In [16]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,47505.0,37.802968,11.834668,5.00,29.0000,38.000,46.00,200.000000
Membership_Years,50000.0,2.984009,2.059105,0.10,1.4000,2.500,4.00,10.000000
Login_Frequency,50000.0,11.624660,7.810657,0.00,6.0000,11.000,17.00,46.000000
Session_Duration_Avg,46601.0,27.660754,10.871013,1.00,19.7000,26.800,34.70,75.600000
Pages_Per_Session,47000.0,8.737811,3.778220,1.00,6.0000,8.400,11.20,24.100000
Cart_Abandonment_Rate,50000.0,57.079973,16.282723,0.00,46.4000,58.100,68.70,143.743350
Wishlist_Items,46000.0,4.298391,3.189754,0.00,2.0000,4.000,6.00,28.000000
Total_Purchases,50000.0,13.111576,7.017312,-13.00,8.0000,12.000,17.00,128.700000
Average_Order_Value,50000.0,123.117330,175.569714,26.38,87.0500,112.970,144.44,9666.379178
Days_Since_Last_Purchase,47000.0,29.792872,29.695062,0.00,9.0000,21.000,41.00,287.000000
Discount_Usage_Rate,46500.0,41.997485,21.373642,0.24,25.3000,40.200,57.00,116.640000
Returns_Rate,45509.0,6.680913,6.143027,0.00,2.9000,5.400,9.10,99.615734
Email_Open_Rate,47472.0,20.937980,14.252561,0.00,9.9000,19.700,30.40,91.700000
Customer_Service_Calls,49832.0,5.681831,2.676052,0.00,4.0000,5.000,7.00,21.000000
Product_Reviews_Written,46500.0,2.853312,2.328948,0.00,1.0000,2.000,4.00,21.000000
Social_Media_Engagement_Score,44000.0,29.364466,20.574021,0.00,13.2000,27.600,43.10,100.000000
Mobile_App_Usage,45000.0,19.371607,9.419252,0.00,12.5000,18.600,25.50,61.900000
Payment_Method_Diversity,47500.0,2.353874,1.110012,1.00,2.0000,2.000,3.00,5.000000
Lifetime_Value,50000.0,1440.626292,907.249443,0.00,789.8175,1243.415,1874.00,8987.240000
Credit_Balance,44500.0,1966.233258,1225.072166,0.00,1049.0000,1896.000,2791.00,7197.000000
Churned,50000.0,0.289000,0.453302,0.00,0.0000,0.000,1.00,1.000000

In [17]:
for col in ["Gender","Country","Signup_Quarter"]:
    print("\n",col)
    print(df[col].value_counts())

 Gender
Gender
Female    25116
Male      23947
Other       937
Name: count, dtype: int64

 Country
Country
USA          17384
UK            7534
Canada        6023
Germany       4925
Australia     4061
France        4013
India         3512
Japan         2548
Name: count, dtype: int64

 Signup_Quarter
Signup_Quarter
Q3    12558
Q2    12521
Q4    12468
Q1    12453
Name: count, dtype: int64

In [18]:
num_cols = df.select_dtypes(include=['float64','int64'])

corr = num_cols.corr()

corr["Churned"].sort_values(ascending=False)

Churned                          1.000000
Customer_Service_Calls           0.291103
Cart_Abandonment_Rate            0.277963
Days_Since_Last_Purchase         0.153360
Returns_Rate                     0.054189
Average_Order_Value              0.042288
Payment_Method_Diversity         0.004524
Membership_Years                -0.000623
Lifetime_Value                  -0.010684
Discount_Usage_Rate             -0.077121
Age                             -0.102849
Credit_Balance                  -0.156921
Total_Purchases                 -0.160029
Product_Reviews_Written         -0.181225
Social_Media_Engagement_Score   -0.191792
Wishlist_Items                  -0.197708
Login_Frequency                 -0.204379
Email_Open_Rate                 -0.222213
Mobile_App_Usage                -0.222876
Session_Duration_Avg            -0.228010
Pages_Per_Session               -0.231799
Name: Churned, dtype: float64

In [19]:
country_churn = pd.crosstab(
    df["Country"],
    df["Churned"],
    normalize="index"
)

country_churn

Churned           0         1
Country
Australia  0.701059  0.298941
Canada     0.706459  0.293541
France     0.727137  0.272863
Germany    0.711675  0.288325
India      0.709852  0.290148
Japan      0.721743  0.278257
UK         0.712105  0.287895
USA        0.709158  0.290842

In [20]:
gender_churn = pd.crosstab(
    df["Gender"],
    df["Churned"],
    normalize="index"
)

gender_churn

Churned         0         1
Gender
Female   0.710264  0.289736
Male     0.712699  0.287301
Other    0.687300  0.312700

In [21]:
num_cols = [
'Login_Frequency',
'Session_Duration_Avg',
'Pages_Per_Session',
'Total_Purchases',
'Average_Order_Value',
'Cart_Abandonment_Rate',
'Customer_Service_Calls',
'Lifetime_Value'
]

for col in num_cols:
    print("\n",col)
    print(df.groupby("Churned")[col].mean())

 Login_Frequency
Churned
0    12.642391
1     9.120830
Name: Login_Frequency, dtype: float64

 Session_Duration_Avg
Churned
0    29.206784
1    23.686822
Name: Session_Duration_Avg, dtype: float64

 Pages_Per_Session
Churned
0    9.297002
1    7.366206
Name: Pages_Per_Session, dtype: float64

 Total_Purchases
Churned
0    13.827522
1    11.350201
Name: Total_Purchases, dtype: float64

 Average_Order_Value
Churned
0    118.383907
1    134.762532
Name: Average_Order_Value, dtype: float64

 Cart_Abandonment_Rate
Churned
0    54.194460
1    64.178935
Name: Cart_Abandonment_Rate, dtype: float64

 Customer_Service_Calls
Churned
0    5.185458
1    6.904378
Name: Customer_Service_Calls, dtype: float64

 Lifetime_Value
Churned
0    1446.805875
1    1425.423236
Name: Lifetime_Value, dtype: float64

In [22]:
num_cols = df.select_dtypes(
    include=['float64','int64']
).columns

for col in num_cols:

    if df[col].isnull().sum()>0:

        median = df[col].median()

        df[col].fillna(
            median,
            inplace=True
        )

C:\Users\Deepti Bhardwaj\AppData\Local\Temp\ipykernel_29448\2607630477.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(

In [23]:
cat_cols = df.select_dtypes(
    include='object'
).columns

for col in cat_cols:

    mode = df[col].mode()[0]

    df[col].fillna(
        mode,
        inplace=True
    )

C:\Users\Deepti Bhardwaj\AppData\Local\Temp\ipykernel_29448\3622789411.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(

In [24]:
df.isnull().sum().sum()

0

In [25]:
df.to_csv(
'cleaned_data.csv',
index=False
)